### ISSUE TITLE
Contactform works ok, but page does not refresh/fields are not cleared/deleted after submitting 

### ISSUE THREAD

**Issue by robbiebak007** [PrestaShop/contactform#15]
Contactform 2.0.2 works ok in Prestashop 1.7.1, but page does not refresh/fields are not cleared/deleted after submitting the message. Customer sees a succes message + the complete contact form they submitted. 

Is there a fix?

**Comment by colinegin** [comment]
@khouloudbelguith do you still reproduce this issue ?

**Comment by khouloudbelguith** [comment]
@robbiebak007, No, I did not manage to reproduce the issue with PS1.7.6.1 & the contactform v4.1.1
https://drive.google.com/file/d/1mIFzMWs2UMi2ot2ZMOz7H7KOzWI6ZNRD/view

Thanks!

**Comment by colinegin** [comment]
Thanks you @khouloudbelguith , I close the issue then ! 
@robbiebak007 feel free to open it again if needed.
