### ISSUE TITLE
contactform module continues to not send email

### ISSUE THREAD

**Issue by maofree** [PrestaShop/contactform#32]
Hi
the function sendMessage inside of contactform.php does not work of version 4.1.1, in many sites
the past version 3.0 works
why do you continue to use this version?

to solve this problem I need to use the past version

thanks

**Comment by maofree** [comment]
I don't get any errors, but the confirm message, but any emails arrive
replacing that function all is ok

**Comment by aecarlosae** [comment]
Hi @maofree, I have tested the module and everything is ok. Perhaps you have a wrong configuration in your email settings. 

Go to you backoffice -> Advanced Parameters -> Email address and scroll down until the "TEST CONFIGURATION E-MAIL", click on the button "Send a test email".

![screenshot-carpinteria cl-2019 07 16-18-56-32](https://user-images.githubusercontent.com/8390579/61335449-739fe780-a7fb-11e9-9f1a-d1094e86b655.png)

Be sure that your setting is similar to:

![screenshot-carpinteria cl-2019 07 16-18-54-33](https://user-images.githubusercontent.com/8390579/61335345-3176a600-a7fb-11e9-9b79-6531ce1cc05d.png)

**Comment by maofree** [comment]
hi
all is ok, it is necessary to set the second option on true on the contactform module to get emails

bye
